/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 完整健康检查
         * @description 检查数据库、内存和磁盘健康状态，用于生产环境监控
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 就绪检查
         * @description 检查应用是否准备好接收流量（仅检查数据库连接）
         */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 存活检查
         * @description 检查应用是否存活（轻量级检查）
         */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有 todos */
        get: operations["TodoController_findAll"];
        put?: never;
        /** 创建新 todo */
        post: operations["TodoController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 根据 ID 获取 todo */
        get: operations["TodoController_findById"];
        put?: never;
        post?: never;
        /** 删除 todo */
        delete: operations["TodoController_delete"];
        options?: never;
        head?: never;
        /** 更新 todo */
        patch: operations["TodoController_update"];
        trace?: never;
    };
    "/api/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有文章列表 */
        get: operations["ArticleController_findAll"];
        put?: never;
        /** 创建草稿文章 */
        post: operations["ArticleController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 发布文章 */
        patch: operations["ArticleController_publish"];
        trace?: never;
    };
    "/api/articles/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 归档文章 */
        patch: operations["ArticleController_archive"];
        trace?: never;
    };
    "/api/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 根据 ID 获取文章详情 */
        get: operations["ArticleController_findById"];
        /** 更新文章内容（仅草稿状态可编辑） */
        put: operations["ArticleController_update"];
        post?: never;
        /** 删除文章 */
        delete: operations["ArticleController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 为文章添加标签 */
        post: operations["ArticleController_addTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{id}/tags/{tag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 移除文章标签 */
        delete: operations["ArticleController_removeTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 根据 Slug 获取文章 */
        get: operations["ArticleController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户注册 */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新访问令牌
         * @description 使用 Refresh Token 获取新的 Access Token（同时轮换 Refresh Token）
         */
        post: operations["AuthController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前会话信息 */
        get: operations["AuthController_getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取会话列表 */
        get: operations["AuthController_listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登出（单设备） */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/revoke-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销指定会话 */
        post: operations["AuthController_revokeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/revoke-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销所有会话 */
        post: operations["AuthController_revokeSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户注册 (v2) */
        post: operations["AuthV2Controller_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 (v2) */
        post: operations["AuthV2Controller_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取当前会话信息 (v2)
         * @description 返回当前会话和用户信息
         */
        get: operations["AuthV2Controller_getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新访问令牌 (v2)
         * @description 使用 Refresh Token 获取新的 Access Token
         */
        post: operations["AuthV2Controller_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户列表 */
        get: operations["UserController_findAll"];
        put?: never;
        /** 创建用户 */
        post: operations["UserController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户详情 */
        get: operations["UserController_findById"];
        put?: never;
        post?: never;
        /** 删除用户 */
        delete: operations["UserController_delete"];
        options?: never;
        head?: never;
        /** 更新用户 */
        patch: operations["UserController_update"];
        trace?: never;
    };
    "/api/dashboard/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取仪表盘统计数据 */
        get: operations["DashboardController_getStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TodoResponseDto: {
            /** @description Todo ID */
            id: string;
            /** @description 标题 */
            title: string;
            /** @description 描述 */
            description: string | null;
            /** @description 是否完成 */
            isCompleted: boolean;
            /**
             * Format: date-time
             * @description 创建时间
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新时间
             */
            updatedAt: string;
        };
        CreateTodoDto: {
            /**
             * @description Todo 标题
             * @example 完成项目文档
             */
            title: string;
            /**
             * @description Todo 描述（可选）
             * @example 编写 API 文档和架构说明
             */
            description?: string;
            /**
             * @description 是否已完成（可选，默认 false）
             * @example false
             */
            isCompleted?: boolean;
        };
        UpdateTodoDto: {
            /**
             * @description Todo 标题
             * @example 完成项目文档
             */
            title?: string;
            /**
             * @description Todo 描述
             * @example 编写 API 文档和架构说明
             */
            description?: string;
            /**
             * @description 是否已完成
             * @example true
             */
            isCompleted?: boolean;
        };
        CreateArticleDto: {
            /**
             * @description 文章标题
             * @example 深入理解依赖倒置原则
             */
            title: string;
            /**
             * @description 文章内容
             * @example 这是一篇关于依赖倒置原则的深度文章...
             */
            content: string;
        };
        ArticleResponseDto: {
            /**
             * @description 文章 ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description 标题
             * @example 深入理解依赖倒置原则
             */
            title: string;
            /**
             * @description 内容
             * @example 这是一篇关于依赖倒置原则的深度文章...
             */
            content: string;
            /**
             * @description URL 友好的 Slug
             * @example shen-ru-li-jie-yi-lai-dao-zhi-yuan-ze
             */
            slug: string;
            /**
             * @description 状态
             * @example draft
             */
            status: Record<string, never>;
            /**
             * @description 标签列表
             * @example [
             *       "DDD",
             *       "Architecture"
             *     ]
             */
            tags: string[];
            /**
             * Format: date-time
             * @description 创建时间
             * @example 2025-01-15T10:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新时间
             * @example 2025-01-15T12:30:00.000Z
             */
            updatedAt: string;
            /**
             * Format: date-time
             * @description 发布时间
             * @example 2025-01-15T14:00:00.000Z
             */
            publishedAt: string | null;
        };
        UpdateArticleDto: {
            /**
             * @description 文章标题
             * @example 深入理解依赖倒置原则（修订版）
             */
            title: string;
            /**
             * @description 文章内容
             * @example 这是修订后的内容...
             */
            content: string;
        };
        AddTagDto: {
            /**
             * @description 标签名称
             * @example DDD
             */
            tag: string;
        };
        RegisterDto: {
            /**
             * Format: email
             * @description 邮箱地址
             * @example user@example.com
             */
            email: string;
            /**
             * @description 用户名（3-30个字符，只能包含字母、数字、下划线和连字符）
             * @example john_doe
             */
            name: string;
            /**
             * @description 密码（至少8个字符，必须包含字母和数字）
             * @example Pass123456
             */
            password: string;
        };
        UserInfo: {
            /** @description 用户ID */
            id: string;
            /** @description 用户邮箱 */
            email: string;
            /** @description 用户角色 */
            role: string | null;
        };
        LoginResponseDto: {
            /** @description Access Token，用于身份验证 */
            accessToken: string;
            /** @description Refresh Token，用于刷新 Access Token */
            refreshToken: string;
            /** @description 用户基本信息 */
            user: components["schemas"]["UserInfo"];
        };
        LoginDto: {
            /**
             * Format: email
             * @description 邮箱地址
             * @example user@example.com
             */
            email: string;
            /**
             * @description 密码
             * @example Pass123456
             */
            password: string;
        };
        RefreshTokenDto: {
            /**
             * Format: uuid
             * @description 登录时返回的 Refresh Token
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            refreshToken: string;
        };
        RefreshTokenResponseDto: {
            /** @description Access Token，用于身份验证 */
            accessToken: string;
            /** @description Refresh Token，用于刷新 Access Token */
            refreshToken: string;
            /** @description 用户基本信息 */
            user: components["schemas"]["UserInfo"];
        };
        SessionUserDto: {
            /** @description 用户ID */
            id: string;
            /** @description 用户邮箱 */
            email: string;
            /** @description 用户角色 */
            role: string | null;
        };
        SessionInfoDto: {
            /** @description 会话ID */
            id: string;
            /**
             * Format: date-time
             * @description 过期时间
             */
            expiresAt: string;
            /** @description IP地址 */
            ipAddress: string | null;
            /** @description 用户代理 */
            userAgent: string | null;
        };
        SessionResponseDto: {
            /** @description 用户信息 */
            user: components["schemas"]["SessionUserDto"];
            /** @description 会话信息 */
            session: components["schemas"]["SessionInfoDto"];
        };
        SessionItemDto: {
            /** @description 会话ID */
            id: string;
            /**
             * Format: date-time
             * @description 创建时间
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 过期时间
             */
            expiresAt: string;
            /** @description IP地址 */
            ipAddress: string | null;
            /** @description 用户代理 */
            userAgent: string | null;
            /** @description 是否为当前会话 */
            isCurrent: boolean;
        };
        SessionsListResponseDto: {
            /** @description 会话列表 */
            sessions: components["schemas"]["SessionItemDto"][];
        };
        LogoutDto: {
            /** @description Refresh Token */
            refreshToken: string;
        };
        LogoutResponseDto: {
            /** @description 是否成功 */
            success: boolean;
            /** @description 消息 */
            message: string;
        };
        RevokeSessionDto: {
            /**
             * Format: uuid
             * @description 要撤销的会话ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            sessionId: string;
        };
        RevokeSessionResponseDto: {
            /** @description 是否成功 */
            success: boolean;
            /** @description 消息 */
            message: string;
        };
        LogoutAllResponseDto: {
            /** @description 撤销的会话数量 */
            revokedCount: number;
            /** @description 消息 */
            message: string;
        };
        UserResponseDto: {
            /**
             * @description 用户 ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description 用户名
             * @example John Doe
             */
            name: string;
            /**
             * @description 显示名称
             * @example John Doe
             */
            displayName: string | null;
            /**
             * @description 邮箱
             * @example john@example.com
             */
            email: string;
            /**
             * @description 邮箱是否已验证
             * @example true
             */
            emailVerified: boolean;
            /**
             * @description 头像 URL
             * @example https://example.com/avatar.png
             */
            image: string | null;
            /**
             * @description 角色
             * @example admin
             */
            role: string | null;
            /**
             * @description 是否被封禁
             * @example false
             */
            banned: boolean;
            /**
             * @description 封禁原因
             * @example 违规操作
             */
            banReason: string | null;
            /**
             * Format: date-time
             * @description 创建时间
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新时间
             * @example 2024-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        UserListResponseDto: {
            /** @description 用户列表 */
            data: components["schemas"]["UserResponseDto"][];
            /**
             * @description 总数
             * @example 100
             */
            total: number;
            /**
             * @description 当前页码
             * @example 1
             */
            page: number;
            /**
             * @description 每页数量
             * @example 20
             */
            pageSize: number;
            /**
             * @description 总页数
             * @example 5
             */
            totalPages: number;
        };
        CreateUserDto: {
            /**
             * @description 用户名（可选）
             * @example John
             */
            name?: string;
            /**
             * @description 显示名称（可选）
             * @example John Doe
             */
            displayName?: string;
            /**
             * Format: email
             * @description 邮箱
             * @example john@example.com
             */
            email: string;
            /**
             * @description 密码
             * @example password123
             */
            password: string;
            /**
             * @description 角色（可选）
             * @example USER
             */
            role?: string;
        };
        UpdateUserDto: {
            /**
             * @description 用户名
             * @example John
             */
            name?: string;
            /**
             * @description 显示名称
             * @example John Doe
             */
            displayName?: string;
            /**
             * @description 角色
             * @example USER
             */
            role?: string;
            /**
             * @description 是否封禁
             * @example false
             */
            banned?: boolean;
            /**
             * @description 封禁原因
             * @example 违规操作
             */
            banReason?: string;
        };
        StatisticsDto: {
            /**
             * @description 总用户数
             * @example 100
             */
            totalUsers: number;
            /**
             * @description 活跃用户数
             * @example 80
             */
            activeUsers: number;
            /**
             * @description 管理员数量
             * @example 5
             */
            adminUsers: number;
            /**
             * @description 今日新增用户数
             * @example 10
             */
            newUsersToday: number;
        };
        ProblemDetailsDto: {
            /**
             * @description 问题类型 URI，应可解引用到人类可读文档
             * @example https://api.example.com/errors/validation-failed
             */
            type: string;
            /**
             * @description 简短的人类可读摘要
             * @example 请求验证失败
             */
            title: string;
            /**
             * @description HTTP 状态码
             * @example 422
             */
            status: number;
            /**
             * @description 针对此次问题实例的详细说明
             * @example 提交的数据未通过业务规则验证
             */
            detail?: string;
            /**
             * @description 问题发生的 URI 引用
             * @example /api/users
             */
            instance?: string;
            /**
             * @description 请求追踪 ID
             * @example req_xyz789
             */
            request_id?: string;
            /**
             * @description 关联 ID（业务事务追踪）
             * @example corr_shop_session_abc123
             */
            correlation_id?: string;
            /**
             * @description 分布式追踪 ID（W3C Trace Context）
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            trace_id?: string;
            /**
             * @description 错误发生时间（ISO 8601格式）
             * @example 2024-11-03T10:30:00Z
             */
            timestamp?: string;
            /**
             * @description 字段级错误数组（验证错误时）
             * @example [
             *       {
             *         "field": "email",
             *         "pointer": "/email",
             *         "code": "INVALID_FORMAT",
             *         "message": "邮箱格式不正确",
             *         "expected_format": "user@domain.com"
             *       }
             *     ]
             */
            errors?: Record<string, never>[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TodoController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功返回 todos 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoResponseDto"][];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TodoController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoDto"];
            };
        };
        responses: {
            /** @description 成功创建 todo */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoResponseDto"];
                };
            };
            /** @description 验证失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TodoController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功返回 todo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoResponseDto"];
                };
            };
            /** @description Todo 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TodoController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功删除 todo */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Todo 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TodoController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTodoDto"];
            };
        };
        responses: {
            /** @description 成功更新 todo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoResponseDto"];
                };
            };
            /** @description Todo 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 验证失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"][];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArticleDto"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 发布成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 业务规则错误（如内容不足 50 字） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 归档成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 业务规则错误（如文章未发布） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateArticleDto"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 业务规则错误（如文章已发布） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_addTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTagDto"];
            };
        };
        responses: {
            /** @description 添加成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 业务规则错误（如超过标签数量限制） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_removeTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
                /** @description 标签名称 */
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 移除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 Slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsListResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeSessionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeSessionResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_revokeSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutAllResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthV2Controller_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthV2Controller_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthV2Controller_getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthV2Controller_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UserController_findAll: {
        parameters: {
            query?: {
                /** @description 搜索关键词（匹配名称或邮箱） */
                search?: string;
                /** @description 按角色筛选 */
                role?: string;
                /** @description 按封禁状态筛选 */
                banned?: boolean;
                /** @description 页码（从1开始） */
                page?: number;
                /** @description 每页数量 */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UserController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description 邮箱已被使用 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UserController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description 用户不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UserController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 用户不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UserController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description 用户不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    DashboardController_getStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatisticsDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
}
