/**
 * Metadata type declarations generated by CLI Plugin
 *
 * metadata.ts is auto-generated by @nestjs/swagger CLI Plugin
 */
declare const metadata: () => Promise<Record<string, unknown>>
export default metadata
